
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    "github.com/apioo/sdkgen-go"
    
    
    
    
)

type Client struct {
    internal *sdkgen.ClientAbstract
}

func (client *Client) People() *PeopleTag {
    return NewPeopleTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Film() *FilmTag {
    return NewFilmTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Starship() *StarshipTag {
    return NewStarshipTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Vehicle() *VehicleTag {
    return NewVehicleTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Specie() *SpecieTag {
    return NewSpecieTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Planet() *PlanetTag {
    return NewPlanetTag(client.internal.HttpClient, client.internal.Parser)
}




func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
    if err != nil {
        return &Client{}, err
    }

	return &Client{
		internal: client,
	}, nil
}

func Build() (*Client, error) {
    var credentials = sdkgen.Anonymous{}

    return NewClient("https://swapi.dev/api", credentials)
}

