
// film automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// A Film is a single film
type Film struct {
    Title string `json:"title"`
    EpisodeId int `json:"episode_id"`
    OpeningCrawl string `json:"opening_crawl"`
    Director string `json:"director"`
    Producer string `json:"producer"`
    ReleaseDate string `json:"release_date"`
    Species []string `json:"species"`
    Starships []string `json:"starships"`
    Vehicles []string `json:"vehicles"`
    Characters []string `json:"characters"`
    Planets []string `json:"planets"`
    Url string `json:"url"`
    Created string `json:"created"`
    Edited string `json:"edited"`
}

