
// people_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type PeopleCollection struct {
    Count int `json:"count"`
    Next string `json:"next"`
    Previous string `json:"previous"`
    Results []People `json:"results"`
}

