
// people automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// A People is an individual person or character within the Star Wars universe
type People struct {
    Name string `json:"name"`
    BirthYear string `json:"birth_year"`
    EyeColor string `json:"eye_color"`
    Gender string `json:"gender"`
    HairColor string `json:"hair_color"`
    Height string `json:"height"`
    Mass string `json:"mass"`
    SkinColor string `json:"skin_color"`
    Homeworld string `json:"homeworld"`
    Films []string `json:"films"`
    Species []string `json:"species"`
    Starships []string `json:"starships"`
    Vehicles []string `json:"vehicles"`
    Url string `json:"url"`
    Created string `json:"created"`
    Edited string `json:"edited"`
}

