
// PlanetTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type PlanetTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll Get all the planets
func (client *PlanetTag) GetAll(search string) (PlanetCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/planets", pathParams))
    if err != nil {
        return PlanetCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return PlanetCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return PlanetCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return PlanetCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data PlanetCollection
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    return PlanetCollection{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Get Get a specific planet
func (client *PlanetTag) Get(id string) (Planet, error) {
    pathParams := make(map[string]interface{})
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/planets/:id", pathParams))
    if err != nil {
        return Planet{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Planet{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Planet{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Planet{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Planet
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    return Planet{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewPlanetTag(httpClient *http.Client, parser *sdkgen.Parser) *PlanetTag {
	return &PlanetTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
