
// root automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Root struct {
    Films string `json:"films"`
    People string `json:"people"`
    Planets string `json:"planets"`
    Species string `json:"species"`
    Starships string `json:"starships"`
    Vehicles string `json:"vehicles"`
}
