
// SpecieTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type SpecieTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll 
func (client *SpecieTag) GetAll(search string) (SpecieCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/species", pathParams))
    if err != nil {
        return SpecieCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return SpecieCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return SpecieCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return SpecieCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response SpecieCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return SpecieCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return SpecieCollection{}, errors.New("the server returned an unknown status code")
    }
}

// Get 
func (client *SpecieTag) Get(id string) (Specie, error) {
    pathParams := make(map[string]interface{})
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/species/:id", pathParams))
    if err != nil {
        return Specie{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Specie{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Specie{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Specie{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response Specie
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return Specie{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return Specie{}, errors.New("the server returned an unknown status code")
    }
}



func NewSpecieTag(httpClient *http.Client, parser *sdkgen.Parser) *SpecieTag {
	return &SpecieTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
