
// StarshipTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type StarshipTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll 
func (client *StarshipTag) GetAll(name string, model string) (StarshipCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["name"] = name
    queryParams["model"] = model

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/starships", pathParams))
    if err != nil {
        return StarshipCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return StarshipCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return StarshipCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return StarshipCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response StarshipCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return StarshipCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return StarshipCollection{}, errors.New("the server returned an unknown status code")
    }
}

// Get 
func (client *StarshipTag) Get(id string) (Starship, error) {
    pathParams := make(map[string]interface{})
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/starships/:id", pathParams))
    if err != nil {
        return Starship{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Starship{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Starship{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Starship{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response Starship
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return Starship{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return Starship{}, errors.New("the server returned an unknown status code")
    }
}



func NewStarshipTag(httpClient *http.Client, parser *sdkgen.Parser) *StarshipTag {
	return &StarshipTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
