
// starship automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"

// A Starship resource is a single transport craft that has hyperdrive capability.
type Starship struct {
    Name string `json:"name"`
    Model string `json:"model"`
    StarshipClass string `json:"starship_class"`
    Manufacturer string `json:"manufacturer"`
    CostInCredits string `json:"cost_in_credits"`
    Length string `json:"length"`
    Crew string `json:"crew"`
    Passengers string `json:"passengers"`
    MaxAtmospheringSpeed string `json:"max_atmosphering_speed"`
    HyperdriveRating string `json:"hyperdrive_rating"`
    MGLT string `json:"MGLT"`
    CargoCapacity string `json:"cargo_capacity"`
    Consumables string `json:"consumables"`
    Films []string `json:"films"`
    Pilots []string `json:"pilots"`
    Url string `json:"url"`
    Created time.Time `json:"created"`
    Edited time.Time `json:"edited"`
}
