
// starship_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type StarshipCollection struct {
    Count int `json:"count"`
    Next string `json:"next"`
    Previous string `json:"previous"`
    Results []Starship `json:"results"`
}
