
// vehicle automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


// A Vehicle is a single transport craft that does not have hyperdrive capability
type Vehicle struct {
    Name string `json:"name"`
    Model string `json:"model"`
    VehicleClass string `json:"vehicle_class"`
    Manufacturer string `json:"manufacturer"`
    Length string `json:"length"`
    CostInCredits string `json:"cost_in_credits"`
    Crew string `json:"crew"`
    Passengers string `json:"passengers"`
    MaxAtmospheringSpeed string `json:"max_atmosphering_speed"`
    CargoCapacity string `json:"cargo_capacity"`
    Consumables string `json:"consumables"`
    Films []string `json:"films"`
    Pilots []string `json:"pilots"`
    Url string `json:"url"`
    Created string `json:"created"`
    Edited string `json:"edited"`
}
