
// VehicleTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type VehicleTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll Get all the vehicles
func (client *VehicleTag) GetAll(search string) (VehicleCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/vehicles", pathParams))
    if err != nil {
        return VehicleCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return VehicleCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return VehicleCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return VehicleCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data VehicleCollection
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    return VehicleCollection{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Get Get a specific vehicle
func (client *VehicleTag) Get(id string) (Vehicle, error) {
    pathParams := make(map[string]interface{})
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/vehicles/:id", pathParams))
    if err != nil {
        return Vehicle{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Vehicle{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Vehicle{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Vehicle{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Vehicle
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    return Vehicle{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewVehicleTag(httpClient *http.Client, parser *sdkgen.Parser) *VehicleTag {
	return &VehicleTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
